spring:
  data:
    redis:
      repositories:
        enabled: false
  r2dbc:
    url: r2dbc:mysql://localhost:3306/escrow?characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: qwer1234